language: node_js
node_js:
- 12.18.3
- 10.22.0
before_script:
- npm install grunt-cli -g
before_install:
- openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
  -in config.json.enc -out config.json -d
